Num = int(input('Digite um número a qual deseja saber a tabuada : '))
print('-'*20)
print('{} x {:2} = {}'.format(Num, 1, Num*1))
print('{} x {:2} = {}'.format(Num, 2, Num*2))
print('{} x {:2} = {}'.format(Num, 3, Num*3))
print('{} x {:2} = {}'.format(Num, 4, Num*4))
print('{} x {:2} = {}'.format(Num, 5, Num*5))
print('{} x {:2} = {}'.format(Num, 6, Num*6))
print('{} x {:2} = {}'.format(Num, 7, Num*7))
print('{} x {:2} = {}'.format(Num, 8, Num*8))
print('{} x {:2} = {}'.format(Num, 9, Num*9))
print('{} x {} = {}'.format(Num, 10, Num*10))
print('-'*20)