a = input('Digite alguma coisa , qualquer coisa mesmo:  ')
print(f'O tipo primitivo desse valor é {type(a)}')
print(f'Tem Somente espaços? {a.isspace()}')
print(f'é somente um valor númerico? {a.isnumeric()}')
print(f'é um valor alfabetico? {a.isalpha()}')
print(f'é um valor alfanumerico? {a.isalnum()}')
print(f'está digitado em tudo maisculo?, {a.isupper()}')
print(f'está digitado em tudo minisculo? {a.islower()}')
print(f'O Valor está capitalizado? {a.istitle()}')