times = ('Atlético-MG','Palmeiras' , 'Fortaleza', 'Bragantino', 'Flamengo', 'Athletico-PR', 'Atlético-GO', 'Ceará SC', 'Internacional', 'Santos', 'Corinthians', 'Juventude', 'Bahia', 'São paulo', 'Fluminense','Cuiabá','Sport Recife', 'América-MG', 'Grêmio', 'Chapecoense')
print ('=-='*20)
print(f'Lista de times do Brasileirão:{times}')
print ('=-='*20)
print(f'Os 5 Primeiros times são {times[0:5]}')
print ('=-='*20)
print(f'Os 4 Ultimos colocados são {times[15:]}')
print ('=-='*20)
print(f'A Chapecoense está em {times.index("Chapecoense")+1}º')
print ('=-='*20)
print(f'A Ordem do time alfabetica é {sorted(times)}')
